DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL UNIQUE,
  verify NUMERIC NOT NULL DEFAULT 0,
  verify_code NUMERIC NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
